# Generated by Django 4.2.16 on 2026-08-11 19:55

import apps.garant.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GarantDeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField(max_length=5000)),
                ('price_crypto', models.DecimalField(decimal_places=8, max_digits=20)),
                ('crypto_currency', models.CharField(choices=[('USDT', 'USDT'), ('TON', 'TON'), ('BTC', 'BTC'), ('ETH', 'ETH'), ('LTC', 'LTC'), ('TRX', 'TRX'), ('BNB', 'BNB')], default='USDT', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('awaiting_buyer', 'Awaiting buyer'), ('awaiting_payment', 'Awaiting payment'), ('paid', 'Paid (funds held)'), ('completed_by_seller', 'Marked complete by seller'), ('confirmed', 'Confirmed by buyer'), ('released', 'Funds released'), ('disputed', 'Disputed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='awaiting_buyer', max_length=32)),
                ('private_link_token', models.CharField(default=apps.garant.models.generate_deal_token, max_length=64, unique=True)),
                ('platform_fee_pct', models.PositiveSmallIntegerField(default=5)),
                ('buyer_agreed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garant_deals_bought', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garant_deals_created', to=settings.AUTH_USER_MODEL)),
                ('room', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garant_deal', to='chat.chatroom')),
            ],
            options={
                'db_table': 'garant_deal',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GarantPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cryptopay_invoice_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('pay_url', models.URLField(blank=True, default='')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('currency', models.CharField(default='USDT', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('expired', 'Expired'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='garant.garantdeal')),
            ],
            options={
                'db_table': 'garant_payment',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GarantDispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=5000)),
                ('evidence_url', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewing', 'Reviewing'), ('resolved_buyer', 'Resolved for buyer'), ('resolved_seller', 'Resolved for seller'), ('rejected', 'Rejected')], default='open', max_length=20)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complainant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garant_disputes', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='garant.garantdeal')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garant_disputes_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'garant_dispute',
                'ordering': ('-created_at',),
            },
        ),
    ]
