# Generated by Django 4.2.16 on 2026-08-11 19:55

import apps.accounts.models
import apps.accounts.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[apps.accounts.validators.validate_email_domain])),
                ('username', models.CharField(max_length=32, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_email_confirmed', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('totp_secret', models.CharField(blank=True, default='', max_length=64)),
                ('totp_enabled', models.BooleanField(default=False)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, default='', max_length=500)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('theme_color', models.CharField(choices=[('gold', 'Gold'), ('graphite', 'Graphite'), ('black', 'Black')], default='gold', max_length=16)),
                ('private_profile', models.BooleanField(default=False)),
                ('paid_messages_enabled', models.BooleanField(default=False)),
                ('paid_message_price', models.PositiveIntegerField(default=0)),
                ('newsletter_opt_in', models.BooleanField(default=False)),
                ('is_18_confirmed', models.BooleanField(default=False)),
                ('tos_confirmed', models.BooleanField(default=False)),
                ('gdpr_data_requested', models.BooleanField(default=False)),
                ('gdpr_data_requested_at', models.DateTimeField(blank=True, null=True)),
                ('telegram_chat_id', models.CharField(blank=True, default='', max_length=64)),
                ('fcm_token', models.CharField(blank=True, default='', max_length=255)),
                ('public_key', models.CharField(blank=True, default='', help_text='Base64 NaCl public key.', max_length=128)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'accounts_user',
                'ordering': ('-date_joined',),
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='InviteLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hash_token', models.CharField(default=apps.accounts.models.generate_invite_token, max_length=64, unique=True)),
                ('max_uses', models.PositiveIntegerField(default=5)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_invite_link',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=2000)),
                ('proof_url', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('reviewer_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_verification_request',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='UserInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rewarded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invite_link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uses', to='accounts.invitelink')),
                ('invitee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invited_by', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_user_invite',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TOTPDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=64)),
                ('confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='totp_device', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_totp_device',
            },
        ),
        migrations.CreateModel(
            name='EmailConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=apps.accounts.models.generate_numeric_code, max_length=6)),
                ('purpose', models.CharField(choices=[('registration', 'Registration'), ('login', 'Login'), ('recovery', 'Recovery')], default='registration', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_email_confirmation',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='accounts_us_usernam_c0ea66_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='accounts_us_phone_f54457_idx'),
        ),
    ]
