# Generated by Django 4.2.16 on 2026-08-14 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_theme_presets'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='displayed_handshake_level',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='show_verified_badge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='username_gradient',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_blocked_user',
                'ordering': ('-created_at',),
                'unique_together': {('blocker', 'blocked')},
            },
        ),
    ]
