# Generated by Django 4.2.16 on 2026-08-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_postattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postattachment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
