# Generated by Django 4.2.16 on 2026-08-14 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='deleted_for_users',
            field=models.ManyToManyField(blank=True, related_name='deleted_chat_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('voice', 'Voice'), ('file', 'File'), ('coin_donation', 'Coin donation'), ('locked_file', 'Locked file'), ('system', 'System')], default='text', max_length=20),
        ),
    ]
