# Generated by Django 4.2.16 on 2026-08-11 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField()),
                ('rarity', models.CharField(choices=[('green', 'Green Handshake'), ('blue', 'Blue Handshake'), ('purple', 'Purple Handshake'), ('red', 'Red Handshake'), ('gold', 'Gold Handshake')], max_length=16)),
                ('transaction_type', models.CharField(choices=[('invite_reward', 'Invite reward'), ('donation', 'Donation'), ('exchange_burn', 'Exchange burn'), ('exchange_mint', 'Exchange mint'), ('paid_message', 'Paid message'), ('file_unlock', 'Locked file unlock'), ('admin_grant', 'Admin grant'), ('activity', 'Activity reward')], max_length=32)),
                ('memo', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coin_transactions_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coin_transactions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coins_transaction',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='InviteReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=10)),
                ('rarity', models.CharField(choices=[('green', 'Green Handshake'), ('blue', 'Blue Handshake'), ('purple', 'Purple Handshake'), ('red', 'Red Handshake'), ('gold', 'Gold Handshake')], default='green', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coins.cointransaction')),
                ('user_invite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward', to='accounts.userinvite')),
            ],
            options={
                'db_table': 'coins_invite_reward',
            },
        ),
        migrations.CreateModel(
            name='HandshakeCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity', models.CharField(choices=[('green', 'Green Handshake'), ('blue', 'Blue Handshake'), ('purple', 'Purple Handshake'), ('red', 'Red Handshake'), ('gold', 'Gold Handshake')], default='green', max_length=16)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coins_handshake_coin',
                'ordering': ('user', 'rarity'),
                'unique_together': {('user', 'rarity')},
            },
        ),
        migrations.AddIndex(
            model_name='cointransaction',
            index=models.Index(fields=['from_user', '-created_at'], name='coins_trans_from_us_8c639f_idx'),
        ),
        migrations.AddIndex(
            model_name='cointransaction',
            index=models.Index(fields=['to_user', '-created_at'], name='coins_trans_to_user_6cff6d_idx'),
        ),
    ]
