# Generated by Django 4.2.16 on 2026-08-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0003_withdrawal_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiatbalance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fiattransaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
