# Generated by Django 4.2.16 on 2026-08-16 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coins', '0004_alter_fiatbalance_id_alter_fiattransaction_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandshakeToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rarity', models.CharField(choices=[('green', 'Green Handshake'), ('blue', 'Blue Handshake'), ('purple', 'Purple Handshake'), ('red', 'Red Handshake'), ('gold', 'Gold Handshake')], db_index=True, default='green', max_length=16)),
                ('is_burned', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minted_handshakes', to=settings.AUTH_USER_MODEL)),
                ('current_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_handshakes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coins_handshake_token',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TokenOwnershipHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='coins.handshaketoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='held_handshakes_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coins_token_ownership_history',
                'indexes': [models.Index(fields=['user', 'token'], name='coins_token_user_id_fc1d7c_idx')],
                'unique_together': {('token', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='handshaketoken',
            index=models.Index(fields=['current_owner', 'rarity', 'is_burned'], name='coins_hands_current_7fe017_idx'),
        ),
    ]
